Gcam macro
JGCRI/gcam-doc pull request #188
Opened 2023-06-04 21:33 UTC by realxinzhao

Two economics-related pages are updated to reflect GCAM-macro updates. They are mainly from the CMP. Links and references are added.

2023-06-05 22:15 UTC, gokuliyer requested changes

2023-06-05 22:15 UTC, gokuliyer commented on economy.md
> +### Connect the Macro Equations to GCAM
I think this section can be removed.

2023-06-05 22:15 UTC, gokuliyer commented on economy.md
> +#### Macro connection to GCAM
This one too.

2023-06-05 22:15 UTC, gokuliyer commented on economy.md
> +#### GCAM connection to Macro
This section can be removed

2023-06-05 22:15 UTC, gokuliyer commented on economy.md
> +### Calculating economic consequences of perturbations in GCAM
This is important and good to have here.

2023-06-05 22:26 UTC, realxinzhao commented on economy.md
> +### Connect the Macro Equations to GCAM
Done. Thanks!

2023-06-05 22:26 UTC, realxinzhao commented on economy.md
> +#### Macro connection to GCAM
Done. Thanks!

2023-06-05 22:26 UTC, realxinzhao commented on economy.md
> +#### GCAM connection to Macro
Done. Thanks!

2023-06-06 12:44 UTC, gokuliyer approved these changes

2023-06-06 13:11 UTC, merged