Add License and Citation files
JGCRI/gcam-doc pull request #205
Opened 2024-04-19 14:06 UTC by pralitp

Add License (to match GCAM) and Citation files

2024-04-24 20:19 UTC, gokuliyer requested changes
Thanks for doing this! Can we do away with authors on the GCAM wiki citation? Should we also call it "GCAM Documentation" instead of "GCAM wiki". The former sounds more formal to me. But that is just my preference.

2024-04-24 20:19 UTC, gokuliyer commented on LICENSE.md
This looks good to me.

2024-04-24 20:19 UTC, gokuliyer commented on CITATION.cff
Can we use a simpler citation without authors instead or is that absolutely required?

2024-04-25 13:02 UTC, pralitp commented on CITATION.cff
I looked up the spec:
https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#authors

The `authors` field is required but we can just give the organization name instead of individuals, so I will do that.

2024-04-25 13:41 UTC, gokuliyer approved these changes

2024-04-25 13:41 UTC, gokuliyer commented on CITATION.cff
> +title: "GCAM Wiki"
Could we call this "GCAM Documentation" instead?

2024-04-25 13:41 UTC, gokuliyer commented
I approve!

2024-04-25 13:41 UTC, merged