Move policy set-up information to policy page.
JGCRI/gcam-doc pull request #57
Opened 2018-11-07 14:19 UTC by ssmithClimate

As per LEC request. Information on linked GHG markets and air-pollutant markets moved to policy page, with a link to that in the emissions page.

2018-11-07 22:33 UTC, d3y419 reviewed
everything else looks great.

2018-11-07 22:33 UTC, d3y419 commented on policies.md
> +## <a name="non-co2-markets"> Markets For non-CO<sub>2</sub> Emission Species</a>
is this the right place for this?

I'd think this should be next to the ghg-link section.
ideally, first intorduce the concept of non-CO2 market, then explain how to link them.

2018-11-07 22:33 UTC, d3y419 commented on policies.md
> +Note that it generally does not make sense to set up an emissions market unless the model has a direct way to reduce emissions! (e.g. you’ve added relevant MAC curves.) For example, in [Shi et al. (2
maybe we do away with exclamation point.

2018-11-09 02:28 UTC, d3y419 approved these changes

2018-11-14 06:19 UTC, d3y419 commented
@pralitp : I don't think I'm allowed to merge this. What's the protocol?

2018-11-14 16:43 UTC, pralitp commented
@d3y419, you need to include one of me, @kvcalvin, or @rplzzz as a reviewer as well.  We can do so final checks and ensure everything fits together correctly and renders properly.  I'll go ahead and add my review.

2018-11-14 16:47 UTC, pralitp requested changes
Just a couple of small things to make the page render better.

There are something things we need to clean up with regards the the emissions page and navigation however since that isn't directly related to this PR I am going to open a separate issue.

2018-11-14 16:47 UTC, pralitp commented on policies.md
> +* [Land-Use Policies](#land-use-policies)
For some reason it renders with a break between this bullet and the previously indented ones.  I'm not sure how to fix that though..

2018-11-14 16:47 UTC, pralitp commented on policies.md
> +One additional MAC-curve option to note is:
Maybe just drop this note and merge the two tables together.  I think it will read and render more cleanly.

2018-11-14 16:47 UTC, pralitp commented on policies.md
> +
Add an extra blank line here to ensure it renders with a break between the end of the table and the start of the next section.

2018-11-16 02:56 UTC, pralitp approved these changes

2018-11-16 02:56 UTC, pralitp commented
@d3y419, can you merge now?

2018-11-16 17:03 UTC, d3y419 commented
"Merging is blocked
The base branch restricts merging to authorized users. "

that's fine. I don't need merging powers. Please go ahead and merge.

2018-11-16 17:38 UTC, merged